name: Prepare Allure
description: Allure installation and folders
runs:
  using: 'composite'
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install allure --fix-missing
        mkdir allure-results
        mkdir allure-report
        mkdir allure-history
      shell: bash
